[build-system]
requires = ["setuptools >= 42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pylint.'MESSAGES CONTROL']
disable = "invalid-name,too-many-locals,too-many-arguments,missing-module-docstring,missing-function-docstring"
